config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'callbacks' }
  root 'manufacturers#index'

  resources :apdks

  resources :users, only: [:index, :show] do
    post :filter, on: :collection
  end

  resources :manufacturers do
    post :filter, on: :collection
  end

  resources :sections do
    resources :categories do
      resources :subcategories do
        resources :manufacturers do
          resources :items do
            resources :modifications do
              post :favourite, on: :collection
            end
            resources :parts
            post :filter, on: :member
          end
        end
      end
    end
  end
end

app/models/part.rb
# frozen_string_literal: true

class Part < ApplicationRecord
  belongs_to :item, inverse_of: :parts
end

app/controllers/parts_controller.rb
# frozen_string_literal: true

class PartsController < ApplicationController
  before_action :check_role, only: [:new, :edit, :create, :update, :destroy]
  before_action :load_part, only: [:edit, :update]

  def new
    @part = Item.new
  end

  def edit
  end

  def create
    @part = Item.new
  end

  def update
    @part.assign_attributes(part_params)

  end

  def destroy

  end

  private

  def check_role
    return if ['super', Manufacturer.cached_by_id[params[:manufacturer_id].to_i].code].include? current_user&.role

    redirect_to section_category_subcategory_manufacturer_item_path(params[:id], section_id: params[:section_id], category_id: params[:category_id], subcategory_id: params[:subcategory_id], manufacturer_id: params[:manufacturer_id])
  end

  def load_part
    @part = Part.find(params[:id])
  end

  def part_params
    params.require(:part).permit(:price, :name, :description)
  end
end

app/views/parts/_form.slim
.columns.is-centered
  .column.is-3
    = link_to 'Назад', root_path, class: 'button is-link is-fullwidth has-text-weight-medium is-medium'
  .column.is-6
    - if @part.errors.any?
      #error_explanation
        h2 = "#{pluralize(@part.errors.count, 'error')} prohibited this device from being saved:"
        ul
          - @part.errors.full_messages.each do |message|
            li = message
  .column.is-3
    = f.submit 'Сохранить', class: 'button is-link is-fullwidth has-text-weight-medium is-medium'
.columns
  .column.is-6
    .field
      = f.label :name, 'Наименование', class: 'label'
      .control = f.text_field :name, class: 'input is-medium'
  .column.is-6
    .field
      = f.label :price, 'Цена', class: 'label'
      .control
        = f.number_field :price, class: 'input is-medium'
.columns
  .column.is-12
    .field
      = f.label :description, 'Описание', class: 'label required'
      .control
        = f.text_field :description, class: 'input is-medium', required: true

app/views/parts/edit.slim
section.has-text-center.has-text-white-50
  .container data-turbo="false"
    = form_with model: @part, url: section_category_subcategory_manufacturer_item_part_path(id: @part.id, item_id: params[:item_id],
            section_id: params[:section_id], category_id: params[:category_id], subcategory_id: params[:subcategory_id], manufacturer_id: params[:manufacturer_id]), remote: false do |f|
      = render 'form', f: f

app/views/parts/new.slim
section.has-text-center.has-text-white-50
  .container
    = form_with model: @part, url: section_category_subcategory_manufacturer_item_parts_path(section_id: params[:section_id], category_id: params[:category_id], subcategory_id: params[:subcategory_id], manufacturer_id: params[:manufacturer_id], item_id: params[:item_id]), remote: false do |f|
      = render 'form', f: f