config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'callbacks' }
  root 'manufacturers#index'

  resources :apdks

  resources :users, only: [:index, :show] do
    post :filter, on: :collection
  end

  resources :manufacturers do
    post :filter, on: :collection
  end

  resources :sections do
    resources :categories do
      resources :subcategories do
        resources :manufacturers do
          resources :items do
            resources :modifications do
              post :favourite, on: :collection
            end
            resources :parts
            post :filter, on: :member
          end
        end
      end
    end
  end
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  belongs_to :subcategory
  belongs_to :manufacturer
  has_many :modifications, inverse_of: :item
  has_many :parts, inverse_of: :item
  accepts_nested_attributes_for :modifications, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :parts, reject_if: :all_blank, allow_destroy: true

  PROPS = [:prop1, :prop2, :prop3].freeze
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  before_action :check_role, only: [:new, :edit, :create, :update]
  before_action :load_item, only: [:show, :filter, :edit, :update]
  before_action :load_all, only: [:show, :filter]

  def index
    @items = Item.where(manufacturer_id: params[:manufacturer_id])
  end

  def show
    @user_mods = current_user&.modifications
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.manufacturer_id = params[:manufacturer_id]
    if @item.save
      redirect_to edit_section_category_subcategory_manufacturer_item_path(@item.id, section_id: params[:section_id], category_id: params[:category_id], subcategory_id: @item.subcategory_id, manufacturer_id: @item.manufacturer_id)
    else
      render new_section_category_subcategory_manufacturer_item_path(params[:id], section_id: params[:section_id], category_id: params[:category_id], subcategory_id: params[:subcategory_id], manufacturer_id: params[:manufacturer_id])
    end
  end

  def edit
  end

  def update
    @item.assign_attributes(item_params)
    if @item.save
      redirect_to section_category_subcategory_manufacturer_item_path(@item.id, section_id: params[:section_id], category_id: params[:category_id], subcategory_id: @item.subcategory_id, manufacturer_id: @item.manufacturer_id)
    else
      render new_section_category_subcategory_manufacturer_item_path(params[:id], section_id: params[:section_id], category_id: params[:category_id], subcategory_id: params[:subcategory_id], manufacturer_id: params[:manufacturer_id])
    end
  end

  def filter
    @reel = params[:parts]&.include?('1')
    @sum += Part.where(id: params[:parts]).sum(&:price)
    json = { sum: @sum, reel: @reel }
    respond_to do |format|
      format.js   { render json: json }
      format.json { render json: json }
    end
  end

  private

  def check_role
    return if ['super', Manufacturer.cached_by_id[params[:manufacturer_id].to_i].code].include? current_user&.role

    redirect_to section_category_subcategory_manufacturer_item_path(params[:id], section_id: params[:section_id], category_id: params[:category_id], subcategory_id: params[:subcategory_id], manufacturer_id: params[:manufacturer_id])
  end

  def load_item
    @item = Item.find(params[:id])
  end

  def load_all
    query = {}
    Item::PROPS.each { |p| query[p.to_sym] = params[p] if params[p] }
    @modifications = @item.modifications
    @grouped_modifications = @modifications.where(query).group_by(&:prop1)
    @mods_parts = query.empty? ? [] : @item.parts.where(code: @modifications.where(query).map(&:part_codes).join(',').split(',').uniq)
    @item_parts = query.empty? ? [] : @item.parts.where(code: @item.part_codes&.split(',')&.uniq)
    @sum = @grouped_modifications.values.first&.first&.price || 0
    @subcategory = @item.subcategory
    @category = @subcategory.category
    @manufacturer = @item.manufacturer
  end

  def item_params
    params.require(:item).permit(:subcategory_id, :name, :prop1, :prop2, :prop3,
      modifications_attributes: %i[id price prop1 prop2 prop3 image_url text _destroy])
  end
end

app/views/items/_filter.slim
- @grouped_modifications&.uniq&.each do |prop, mods|
  - mods.each do |mod|
    .card
      .card-content
        .media
          .media-left
            figure.image.is-48x48
              - if current_user
                - route = favourite_section_category_subcategory_manufacturer_item_modifications_path(modification_id: mod.id, manufacturer_id: @item.manufacturer.id, item_id: @item.id, prop1: params[:prop1], prop2: params[:prop2], prop3: params[:prop3])
                - if @user_mods&.find_by(id: mod.id)
                  = link_to route, data: { 'turbo-method': :post } do
                    i.fas.fa-star
                - else
                  = link_to route, data: { 'turbo-method': :post } do
                    i.far.fa-star
          .media-content
            p.title = "#{@item.name} #{mod.prop1}"
            p.subtitle = "₽#{mod.price}"
      .card-image
        - if mod.images
          - mod.images.split(",").map { |z| (!@reel && z.to_i == 19) ? '00' : z.to_i.to_s.rjust(2, "0") }.each_slice(@item.img_divider) do |image_part|
            .xxx
              - image_part.each do |i|
                = link_to "/assets/manufacturers/#{@item.manufacturer.code}/#{@item.code}/image_part_#{i}.jpg" do
                  = image_tag "manufacturers/#{@item.manufacturer.code}/#{@item.code}/image_part_#{i}.jpg", style: "width: #{ 100 / @item.img_divider }%;"
        - elsif mod.image_url
          = link_to mod.image_url do
            = image_tag mod.image_url, style: 'width: 100%;', class: 'bordered logo'

      .card-content
        .content
          = mod.text

- url = filter_section_category_subcategory_manufacturer_item_path(Section.podvoh, @category.id, @subcategory.id, @manufacturer.id, @item.id)
javascript:
    function checkboxes() {
        return document.querySelectorAll('.manufacturer');
    }

    var myFunction = function (event) {
        true_checkboxes = Array.prototype.slice.call(checkboxes()).filter(ch => ch.checked);
        parts = true_checkboxes.map((el, i) => {if (el.checked) return el.dataset.id });
        params = {parts: parts};
        searchParams = new URLSearchParams(window.location.search);
        if (searchParams.has('prop1')) params.prop1 = searchParams.get('prop1');
        if (searchParams.has('prop2')) params.prop2 = searchParams.get('prop2');
        if (searchParams.has('prop3')) params.prop3 = searchParams.get('prop3');
        xhr = new XMLHttpRequest();
        xhr.open("POST", "#{url}");
        xhr.setRequestHeader("Accept", "application/json");
        xhr.setRequestHeader("Content-Type", "application/json");
        xhr.setRequestHeader("X-CSRF-Token", document.querySelector('meta[name="csrf-token"]').content);
        xhr.onload = () => {
            data = JSON.parse(xhr.response)
            document.getElementById("sum").innerHTML = `₽${data.sum}`;
        };
        xhr.send(JSON.stringify(params));
    };

    for (var i = 0; i < checkboxes().length; i++) {
        checkboxes()[i].addEventListener('change', myFunction, false);
    }

app/views/items/_form.slim
.columns.is-centered
  .column.is-3
    = link_to 'Назад', root_path, class: 'button is-link is-fullwidth has-text-weight-medium is-medium'
  .column.is-6
    - if @item.errors.any?
      #error_explanation
        h2 = "#{pluralize(@item.errors.count, 'error')} prohibited this device from being saved:"
        ul
          - @item.errors.full_messages.each do |message|
            li = message
  .column.is-3
    = f.submit 'Сохранить', class: 'button is-link is-fullwidth has-text-weight-medium is-medium'
.columns
  .column.is-4
    .field
      = f.label :subcategory_id, 'Категория', class: 'label'
      .control
        = f.select :subcategory_id, Subcategory.all_cached.map { |x| [x.name, x.id] }, {}, class: 'input is-medium'
  .column.is-8
    .field
      = f.label :name, 'Наименование', class: 'label'
      .control = f.text_field :name, class: 'input is-medium'
.columns
  .column.is-4
    .field
      = f.label :prop1, '1-ое свойство', class: 'label required'
      .control
        = f.text_field :prop1, class: 'input is-medium', id: :prop1, required: true
  .column.is-4
    .field
      = f.label :prop2, '2-ое свойство', class: 'label required'
      .control
        = f.text_field :prop2, class: 'input is-medium', id: :prop2
  .column.is-4
    .field
      = f.label :prop3, '3-е свойство', class: 'label required'
      .control
        = f.text_field :prop3, class: 'input is-medium', id: :prop3

app/views/items/_modification_fields.slim
.nested-fields
  .card.has-background-primary-light
    .card-table
      .columns
        .column.is-4
          .field.is-vertical
            label.label
              | Модификация
            .field-body
              .field
                p.control
                  = f.number_field :id, class: 'input', disabled: true
        .column.is-4
          .field.is-vertical
            label.label
              | Цена
            .field-body
              .field
                p.control
                  = f.number_field :price, class: 'input'
        .column.is-4
          = link_to_remove_association 'Удалить', f, class: 'button is-small is-danger'
      .columns
        .column.is-4
          .field.is-vertical
            label.label.prop1
              | 1-ое свойство
            .field-body
              .field
                p.control
                  = f.text_field :prop1, class: 'input'
        .column.is-4
          .field.is-vertical
            label.label.prop2
              | 2-ое свойство
            .field-body
              .field
                p.control
                  = f.text_field :prop2, class: 'input'
        .column.is-4
          .field.is-vertical
            label.label.prop3
              | 3-е свойство
            .field-body
              .field
                p.control
                  = f.text_field :prop3, class: 'input'
      .columns
        .column.is-3 = 'Фото'
        .column.is-9 = f.text_field :image_url, class: 'control input'
      .columns
        .column.is-3 = f.label :text, 'Описание'
        .column.is-9 = f.text_area :text, class: 'input is-small', placeholder: 'Описание', rows: 5, cols: 5
  p

app/views/items/edit.slim
section.has-text-center.has-text-white-50
  .container data-turbo="false"
    = form_with model: @item, url: section_category_subcategory_manufacturer_item_path(id: @item.id,
            section_id: params[:section_id], category_id: params[:category_id], subcategory_id: params[:subcategory_id], manufacturer_id: params[:manufacturer_id]), remote: false do |f|
      = render 'form', f: f
      #modifications
        = f.fields_for :modifications do |modification|
          = render 'modification_fields', f: modification
        .links
          = turbo_frame_tag f
          = link_to_add_association 'Добавить модификацию', f, :modifications, class: 'button is-small is-link'

javascript:
    HTMLCollection.prototype.forEach = HTMLCollection.prototype.forEach || function (callBack) {
        for (let i = 0; i < this.length; i++) { callBack(this[i]) }
    };
    ['prop1', 'prop2', 'prop3'].forEach((name) => {
        let value = document.getElementById(name)
        if (value.value) window.onload = set_prop(name, value.value)
        value.addEventListener('change', function() { set_prop(name, this.value) });
    })
    function set_prop(name, text) {
        document.getElementsByClassName(name).forEach((el) => {el.textContent = text})
    }

app/views/items/filter.js.erb
$('.filter').html("<%= j render partial: 'filter' %>");
$('#sum').html("₽<%= @sum %>")
$('#sum_percent').css({ width: "<%= @sum / 300 %>%" });

app/views/items/index.slim
section.has-text-center.has-text-white-50
  .container
    - @items.each do |item|
      p = link_to "Редактировать \"#{item.name}\"", edit_section_category_subcategory_manufacturer_item_path(id: item.id,
              section_id: params[:section_id], category_id: params[:category_id], subcategory_id: params[:subcategory_id], manufacturer_id: params[:manufacturer_id])

app/views/items/new.slim
section.has-text-center.has-text-white-50
  .container
    = form_with model: @item, url: section_category_subcategory_manufacturer_items_path(section_id: params[:section_id], category_id: params[:category_id], subcategory_id: params[:subcategory_id], manufacturer_id: params[:manufacturer_id]), remote: false do |f|
      = render 'form', f: f

app/views/items/show.slim
section.has-text-center.has-text-white-50
  .container
    h1.title#sum = "₽#{@sum}"
    p = link_to 'Убрать фильтр', section_category_subcategory_manufacturer_item_path(Section.podvoh, @category.id, @subcategory.id, @item.manufacturer.id, @item.id), class: 'btn btn-block btn-outline-danger'
    .columns
      .column.is-6
        .columns
          .column.is-4
            - Item::PROPS.each do |prop|
              - property = @item.send(prop)
              - next unless property
              .has-text-center
                .d-flex.h-100
                  .project-text.w-100.my-auto.has-text-center class="text-lg-left"
                    table.table-sm
                      .btn.btn-block.btn-outline-primary.disabled aria-disabled="true" = property
                      tbody
                        - uniq = []
                        - @grouped_modifications.each do |pr, mods|
                          - query = {}
                          - Item::PROPS.each { |p| query[p] = params[p] if params[p] }
                          - mods.uniq { |x| x.send(prop) }.each do |mod|
                            - m = mod.send(prop)
                            - query[prop.to_sym] = m
                            - next if uniq.include? m
                            - uniq << m
                            - if m
                              tr
                                td = link_to m, section_category_subcategory_manufacturer_item_path(Section.podvoh, @category.id, @subcategory.id, @item.manufacturer.id, @item.id, query), class: "btn btn-block btn-#{(params[prop] == m.to_s ? "" : "outline-")}primary"

          .column.is-4
            .has-text-center
              .d-flex.h-100
                .project-text.w-100.my-auto.has-text-center class="text-lg-left"
                  = form_tag '', id: 'parts_form', remote: true
                  - { 'Индивидуально' => @mods_parts, 'Дополнительно' => @item_parts}.each do |key, parts|
                    - if parts.present?
                      table.table-sm
                        thead = "#{key}:"
                        tbody
                        .form-check
                          - parts.sort.each do |mod_part|
                            .custom-control.custom-checkbox
                              div style='white-space: nowrap;'
                                input.custom-control-input type="checkbox" id="mod_part_#{mod_part.id}" class="manufacturer" data-id="#{mod_part.id}"
                                label.custom-control-label for="mod_part_#{mod_part.id}"
                                  sup.has-text-right.has-text-primary = "+#{mod_part.price} "
                                  = mod_part.name
      .column.is-6
        .filter
          = render partial: 'filter'