config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'callbacks' }
  root 'manufacturers#index'

  resources :apdks

  resources :users, only: [:index, :show] do
    post :filter, on: :collection
  end

  resources :manufacturers do
    post :filter, on: :collection
  end

  resources :sections do
    resources :categories do
      resources :subcategories do
        resources :manufacturers do
          resources :items do
            resources :modifications do
              post :favourite, on: :collection
            end
            resources :parts
            post :filter, on: :member
          end
        end
      end
    end
  end
end

app/models/manufacturer.rb
# frozen_string_literal: true

class Manufacturer < ApplicationRecord
  include Dictionary
  has_many :items

  has_many :manufacturer_subcategories
  has_many :subcategories, through: :manufacturer_subcategories, inverse_of: :manufacturers, dependent: :destroy
end

app/controllers/manufacturers_controller.rb
# frozen_string_literal: true

class ManufacturersController < ApplicationController
  def index
    @flags = (['ru', 'ua', 'by'] + Manufacturer.pluck(:country).uniq.sort).uniq
    scope = Manufacturer.all
    scope = scope.where(country: params[:flag]) if params[:flag]
    @manufacturers = scope.order(id: :asc)
  end

  def show
    @manufacturer = Manufacturer.find(params[:id])
    @items = @manufacturer.items
    @subcategory = Subcategory.cached_by_id[@manufacturer.subcategories.first&.id]
    @category = @subcategory&.category
    @parts = Part.where(item_id: @items.map(&:id))
  end
end

app/views/manufacturers/index.slim
section.is-mobile
  .columns
    .column.is-12
      = link_to 'Все', manufacturers_path
      | &nbsp
      - @flags.each do |flag|
        = link_to manufacturers_path(flag: flag) do
          - next if flag.blank?
          span class="flag-icon flag-icon-#{flag}" alt="#{flag}"
        | &nbsp
      = link_to 'Другие', manufacturers_path(flag: '')
section
  .filter
    - @manufacturers.each_slice(4) do |batch|
      .columns
        - batch.each do |manufacturer|
          .column.is-3
            .card.has-background-primary-light
              header.card-header
                p.card-header-title
                  span style="white-space: nowrap;" = manufacturer.name
                a.card-header-icon
                  span class="flag-icon flag-icon-#{manufacturer.country}"
              .card-content style="background-color: #{manufacturer.background_color};"
                .content style="height: 100px"
                  = link_to manufacturer_path(manufacturer.id) do
                    = image_tag "manufacturers/logo/#{manufacturer.code}.jpg", size: '250x250'

app/views/manufacturers/show.slim
section.has-text-center
  .container
    .columns
      .column.is-3
        .card
          header.card-header
            p.card-header-title
              = @manufacturer.name
            a.card-header-icon aria-label=("more options") href="#"
              span class="flag-icon flag-icon-#{@manufacturer.country}"
          .card-content style="background-color: #{@manufacturer.background_color};"
            .content style="height: 180px"
              = link_to manufacturer_path(@manufacturer.id) do
                = image_tag "manufacturers/logo/#{@manufacturer.code}.jpg", size: '250x250'
      .column.is-4
        div.has-text-left.has-text-white-50
          div
            small Оф.сайт:
            small &nbsp
            small = link_to @manufacturer.www, 'https://' + @manufacturer.www
          div
            small Email:
            small &nbsp
            small = link_to @manufacturer.email, @manufacturer.email
          div
            small Тел:
            small &nbsp
            small = link_to @manufacturer.phone, '#'
          div
            small Адрес:
            small &nbsp
            small = link_to @manufacturer.address, '#'
          - if @manufacturer.catalog.present?
            div
              small Каталог:
              small &nbsp
              small = link_to 'Скачать', @manufacturer.catalog
    - @items.each_slice(4) do |batch|
      .columns
        - batch.each do |item|
          .column.is-3
            .card.has-background-primary-light
              header.card-header
                p.card-header-title
                  span style="white-space: nowrap;" = item.name
              - if ['super', Manufacturer.cached_by_id[@manufacturer.id].code].include? current_user&.role
                .card-content
                  p= link_to 'Просмотр', section_category_subcategory_manufacturer_item_path(Section.podvoh, item.subcategory.category.id, item.subcategory.id, item.manufacturer.id, item.id)
                  p= link_to 'Редактировать', edit_section_category_subcategory_manufacturer_item_path(item.id, section_id: Section.podvoh, category_id: item.subcategory.category.id, subcategory_id: item.subcategory.id, manufacturer_id: item.manufacturer.id)
    - if ['super', Manufacturer.cached_by_id[@manufacturer.id].code].include? current_user&.role
      - @parts.each_slice(4) do |batch|
        .columns
          - batch.each do |part|
            - item = part.item
            .column.is-3
              .card.has-background-primary-light
                header.card-header
                  p.card-header-title
                    span style="white-space: nowrap;" = link_to part.name, edit_section_category_subcategory_manufacturer_item_part_path(part.id, section_id: Section.podvoh, category_id: item.subcategory.category.id, subcategory_id: item.subcategory.id, manufacturer_id: item.manufacturer.id,  item_id: part.item_id)