config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'callbacks' }
  root 'manufacturers#index'

  resources :apdks

  resources :users, only: [:index, :show] do
    post :filter, on: :collection
  end

  resources :manufacturers do
    post :filter, on: :collection
  end

  resources :sections do
    resources :categories do
      resources :subcategories do
        resources :manufacturers do
          resources :items do
            resources :modifications do
              post :favourite, on: :collection
            end
            resources :parts
            post :filter, on: :member
          end
        end
      end
    end
  end
end

app/views/layouts/_footer.slim
footer
  .content.has-text-centered
    br
    p
      a.tag.is-link href='https://t.me/dvitvitskiy' Telegram
      - Common.sites.each do |name, str|
        = link_to "https://#{name}", class: 'mx-2' do
          i class="#{str}"
      a.tag.is-link href="mailto:dvitvitskiy.pro@gmail.com" Email
    p
      | The source code is licensed
      a href="http://opensource.org/licenses/mit-license.php"  MIT
      | &nbsp
      | Copyright &copy;
      = " 2019-#{Time.now.year}"
    br

app/views/layouts/_header.slim
section.hero.is-info.welcome.is-small
  .hero-body
    .container
      .columns
        .column.is-4
          h1.title
            = link_to 'podvoh.krsz.ru', root_path
        - if current_user
          .column.is-4
            h2.subtitle.is-pulled-right
              = link_to user_path(current_user.id) do
                i.far.fa-user
                | &nbsp
                = current_user.email || current_user.phone
          .column.is-4
            h2.subtitle.is-pulled-right
              = link_to destroy_user_session_path, data: { 'turbo-method': :delete } do
                i.fa-solid.fa-right-from-bracket
        - else
          .column.is-3
            h2.subtitle
              script src="https://telegram.org/js/telegram-widget.js?21" data-telegram-login="ruPodvohXYZBot" data-size="large" data-radius="10" data-auth-url="/users/auth/telegram" data-request-access="write"
          / .column.is-3
          /   h2.subtitle
          /     = link_to omniauth_authorize_path(:user, :yandex) do
          /       = "Войти через"
          /       | &nbsp
          /       i.fab.fa-yandex
          /       = "ндекс"
          / .column.is-3
          /   h2.subtitle
          /     = link_to omniauth_authorize_path(:user, :telegram) do
          /       = "Войти через"
          /       | &nbsp
          /       i.fab.fa-telegram
          /       | &nbsp
          /       = "Telegram"

/ = image_tag 'redmask2.png', class: 'brand-image'
/ = link_to 'Телеграм-канал "podvoh.krsz.ru"', 'https://t.me/podvoh_xyz', class: 'navbar-item', target: :_blank

app/views/layouts/application.slim
doctype html
html
  head
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
    = javascript_include_tag 'application', 'data-turbo-track': 'reload', defer: true
    = favicon_link_tag asset_path('favicon.png')

    title podvoh.krsz.ru
    meta charset="utf-8"
    meta name="yandex-verification" content="b8209de9862994b1"
    / meta name="viewport"            content="width=device-width,initial-scale=1"
    meta name="description"         content="podvoh.krsz.ru"
    meta name="twitter:card"        content="summary_large_image"
    meta property="og:url"          content="https://podvoh.krsz.ru/"
    meta property="og:site_name"    content="podvoh.krsz.ru"
    meta property="og:type"         content="website"
    meta property="og:title"        content="podvoh.krsz.ru"
    meta property="og:locale"       content="ru_RU"
    meta property="og:description"  content="podvoh.krsz.ru"
    meta property="og:image"        content="#{asset_path('og-image.png')}"
    meta content="IE=edge"          http-equiv="X-UA-Compatible"
    link rel="canonical"  href="https://podvoh.krsz.ru"
    link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
    link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@400;600;800&display=swap"

  body
    = render 'layouts/header'
    section.section
      .container
        .columns
          .column.is-3
            aside.is-medium.menu
              - Category.eager_load(:subcategories).where(section_id: Section.podvoh).each do |category|
                p.menu-label
                  i.nav-icon class="#{category.klass}"
                  | &nbsp
                  = category.name
                ul.menu-list
                  - category.subcategories.each do |subcategory|
                    li
                      = link_to section_category_subcategory_path(Section.podvoh, category.id, subcategory.id), class: 'nav-link' do
                        i.nav-icon class="#{subcategory.klass}"
                        | &nbsp
                        = subcategory.name
          .column.is-9
            nav.breadcrumb aria-label="breadcrumbs"
              ul
                - if @category
                  li class="#{'is-active' unless @subcategory}"
                    = link_to @category.name, section_category_path(Section.podvoh, @category.id), class: 'navbar-item'
                - if @subcategory
                  li class="#{'is-active' unless @manufacturer}"
                    = link_to @subcategory.name, section_category_subcategory_path(Section.podvoh, @category.id, @subcategory.id), class: 'navbar-item'
                - if @manufacturer && @category && @subcategory
                  li class="#{'is-active' unless @item}"
                    = link_to @manufacturer.name, section_category_subcategory_manufacturer_path(Section.podvoh, @category.id, @subcategory.id, @manufacturer.id), class: 'navbar-item'
                - if @item && @category && @subcategory
                  li.is-active
                    = link_to @item.name, section_category_subcategory_manufacturer_item_path(Section.podvoh, @category.id, @subcategory.id, @manufacturer.id, @item.id), class: 'navbar-item'
            = yield
    = render 'layouts/footer'

javascript:
    if ("#{Rails.env}" == 'production') {
        (function (m, e, t, r, i, k, a) {
            m[i] = m[i] || function () { (m[i].a = m[i].a || []).push(arguments) };
            m[i].l = 1 * new Date();
            k = e.createElement(t), a = e.getElementsByTagName(t)[0], k.async = 1, k.src = r, a.parentNode.insertBefore(k, a)
        })
        (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");
        ym(72064657, "init", {clickmap: true, trackLinks: true, accurateTrackBounce: true, webvisor: true});
    }